version: ~> 1.0
language: ruby
os: linux
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet --trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "Cy1ruwYl9lp3uHhXvUa+iQdlaQCwPRINamQ7l8TdqN//+TZaf85KR/VJkqGyEgzn3h97R4kVSt9zFOrydOK4sEio0EaIHEI66gxjVoWZhkhbO2/l3fqrIAGg9+7yMx3+kNGApmyjwx9XR6oNofegxO2WVlGOm2zIh4V7hyRwupvPpJkIdzCcIrp5HEsmhfo5geNdlbyio0mLB63gwEcLFgO/+uGka2AmMbhm12v/+FtQ7Uei1exSXIXlqPYG8uU7QYiwQECtF/h/1O4Ixb6/+xJyiui6aYm+6lD+MxXId4S6jQ9UEgFmczKpENzajydiXG3vp6itqKEa0uoz689GkBFnEWYrEMMsSgemkLqyOsHe+atymO4nLgGbGjVDYAmVKFFt4yWbfohrPCj4PvKCtup37s1GKvCmNiRujLDa36s5McwS8UbgpfSLSQCVRyjjps1VZCsekEPSEPgux91Ma4J+ZULt1kqvG/IPoLB8UnrcxAyzplsqKj9lsw1LQnzI3/kIu/QtTdO+Z20yFQolpc1SAN/5KYgoNMbO0PhO64n5VT1cSIX6J+XBRgR/gNR341eZELgrd0vdAcggC26fBpcAixE/w4GbmH3Kf1EAZI9XzFGKMPSqBwks/BZ1wXFr7Thom7nBpHsq1IDaTJq2r7BbYEFPdGyP/4nxEv/g5xo="
branches:
  only:
    - master
